- hosts: localhost
  vars:
    _src_galaxy_root: "{{ src_galaxy_root | default('/srv/galaxy') }}" # component variable src_galaxy_root
    galaxy_config_style: yaml
    galaxy_layout: custom
    galaxy_server_dir: "{{ _src_galaxy_root }}/server"
    galaxy_root_dir: "{{ galaxy_server_dir }}" # workaround https://github.com/galaxyproject/ansible-galaxy/issues/138
    galaxy_venv_dir: "{{ _src_galaxy_root }}/venv"
    galaxy_config_dir: "{{ _src_galaxy_root }}/config"
    galaxy_mutable_data_dir: "{{ src_galaxy_storage_path | default(_src_galaxy_root+'/datadir') }}" # component variable src_galaxy_storage_path
    galaxy_manage_systemd: yes
    galaxy_commit_id: "v{{ src_galaxy_version | default('24.0.0') }}" # component variable src_galaxy_version
    galaxy_separate_privileges: yes
    galaxy_create_user: yes
    galaxy_manage_paths: yes
    galaxy_user: galaxy
    galaxy_privsep_user: gxpriv
    galaxy_group: galaxy
    galaxy_client_use_prebuilt: yes
    postgresql_objects_users:
      - name: galaxy
        password: null
    postgresql_objects_databases:
      - name: galaxy
        owner: galaxy
    galaxy_config:
      galaxy:
        use_remote_user: true
        database_connection: "postgresql:///galaxy?host=/var/run/postgresql"
      gravity:
        process_manager: systemd
        gunicorn:
          # listening options
          bind: "unix:{{ _src_galaxy_root }}/gunicorn.sock"
          # performance options
          workers: 2
          # Other options that will be passed to gunicorn
          # This permits setting of 'secure' headers like REMOTE_USER (and friends)
          # https://docs.gunicorn.org/en/stable/settings.html#forwarded-allow-ips
          extra_args: '--forwarded-allow-ips="*"'
          # This lets Gunicorn start Galaxy completely before forking which is faster.
          # https://docs.gunicorn.org/en/stable/settings.html#preload-app
          preload: true
        celery:
          concurrency: 2
          loglevel: DEBUG
        handlers:
          handler:
            processes: 2
            pools:
              - job-handlers
              - workflow-schedulers
  pre_tasks:
    - name: Install Dependencies
      apt:
        name: ['git', 'python3-psycopg2', 'python3-virtualenv', 'acl', 'supervisor']
      become: yes
    - name: Run supervisord
      service:
        name: supervisor
        state: started
      become: yes
      become-user: "{{ galaxy_user }}"
  tasks:
    - include_role: {name: install_roles } # workaround to install requirements.yml on SRC
    - include_role:
        name: galaxyproject.postgresql
        apply:
          become: yes
    - include_role:
        name: galaxyproject.postgresql_objects
        apply:
          become: yes
          become_user: postgres
    - include_role: { name: galaxyproject.galaxy }
  roles:
    - role: nginx-reverse_proxy
      vars:
        nginx_reverse_proxy_locations:
          - name: galaxy
            location: /
            backend: http://localhost:8080/
            auth: sram
          - name: static
            location: /static
            alias: "{{ galaxy_server_dir }}/static"
          - name: static_plugins
            location: "~ ^/plugins/(?<plug_type>.+?)/(?<vis_name>.+?)/static/(?<static_file>.*?)$"
            expires: '24'
