# You can use this file to pass in parameters when testing the playbook locally, with something like:
# ansible-playbook -i localhost, -c local -e "@parameters.yml" -vv galaxysrv.yml
# Note: define booleans as strings to simulare behavior on ResearchCloud.
src_galaxy_bootstrap: 'false'
src_galaxy_interactive_tools: 'false'
workspace_fqdn: ubuntu2204mire
src_galaxy_cvmfs: 'true'
src_galaxy_jobs_default: singularity
