---
roles:
  - src: https://github.com/galaxyproject/ansible-galaxy.git
    name: galaxyproject.galaxy
    version: 08974b18e2aad1e5569854e5d6c8b5c966bf55e4
  - src: https://github.com/dometto/ansible-galaxy-tools.git
    name: galaxyproject.galaxy-tools
  - src: galaxyproject.postgresql
    version: 1.1.2
  - src: galaxyproject.postgresql_objects
    version: 1.2.0
  - src: galaxyproject.miniconda
    version: 0.3.1

collections:
  - name: community.general
  - name: community.postgresql
  - name: https://github.com/UtrechtUniversity/researchcloud-items.git
    type: git
    version: cdc876defd67db078a5a5e1a64f485a18aea586f
