---
roles:
  - src: https://github.com/dometto/ansible-galaxy.git
    version: prebuilt_client
    name: galaxyproject.galaxy
  - src: https://github.com/dometto/ansible-galaxy-tools.git
    name: galaxyproject.galaxy-tools
  - src: galaxyproject.postgresql
    version: 1.1.2
  - src: galaxyproject.postgresql_objects
    version: 1.2.0
  - src: galaxyproject.miniconda
    version: 0.3.1

collections:
  - name: community.general
  - name: community.postgresql
  - name: https://github.com/UtrechtUniversity/researchcloud-items.git
    type: git
