---
roles:
  - src: https://github.com/galaxyproject/ansible-galaxy.git
    name: galaxyproject.galaxy
    version: 08974b18e2aad1e5569854e5d6c8b5c966bf55e4
  - src: https://github.com/dometto/ansible-galaxy-tools.git
    name: galaxyproject.galaxy-tools
  - src: galaxyproject.postgresql
    version: 1.1.2
  - src: galaxyproject.postgresql_objects
    version: 1.2.0
  - src: galaxyproject.miniconda
    version: 0.3.1
  - src: geerlingguy.docker
    version: 6.1.0

collections:
  - name: community.general
  - name: community.postgresql
  - name: https://github.com/UtrechtUniversity/researchcloud-items.git
    type: git
    version: a20effebee6e395b81c3dd72963bf87a1f99a80b
