---
- name: Get user defined tools and workflows from a custom git repo
  when: _galaxy_custom_repo | length > 0
  block:

    - name: Clone the git repo
      ansible.builtin.git:
        repo: "{{ _galaxy_custom_repo }}"
        version: "{{ _galaxy_custom_repo_branch }}"
        dest: "{{ _galaxy_custom_repo_clone_dest }}"
        depth: 1
        update: true

    - name: Find all tools in repo
      ansible.builtin.find:
        paths: "{{ _galaxy_custom_repo_clone_dest }}/{{ _galaxy_custom_repo_tool_location }}"
        file_type: file
        patterns: ['*.yml', '*.yaml']
      register: _galaxy_custom_repo_tool_files

    - name: Set custom tool files array
      set_fact:
        _galaxy_custom_tool_files: "{{ _galaxy_custom_repo_tool_files['files'] | map(attribute='path') | list | default([]) }}"

    - name: Find all workflows in repo
      ansible.builtin.find:
        paths: "{{ _galaxy_custom_repo_clone_dest }}/{{ _galaxy_custom_repo_workflow_location }}"
        file_type: file
        patterns: ['*.ga']
      register: _galaxy_custom_repo_workflow_files

    - name: Set custom workflow files array
      set_fact:
        _galaxy_custom_workflow_files: "{{ _galaxy_custom_repo_workflow_files['files'] | map(attribute='path') | list | default([]) }}"

- name: Install tools and workflows
  ansible.builtin.include_role:
    name: galaxyproject.galaxy-tools
  vars:
    galaxy_tools_base_dir: "{{ galaxy_root }}"
    galaxy_tools_api_key: "{{ galaxy_config.galaxy.bootstrap_admin_api_key }}"
    galaxy_tools_install_tools: true
    galaxy_tools_install_workflows: true
    galaxy_tools_galaxy_instance_url: "{{ _galaxy_nginx_hostname }}"
    galaxy_tools_tool_list_files: "{{ _galaxy_tool_files + (_galaxy_custom_tool_files | default([])) }}"
    galaxy_tools_workflows: "{{ _galaxy_workflow_files + (_galaxy_custom_workflow_files | default([])) }}"
