---
- name: Converge
  hosts: all
  gather_facts: false

- name: Run playbook as test
  ansible.builtin.import_playbook: ../../galaxysrv.yml
  vars:
    src_galaxy_tool_files:
      - ../_testfiles/tool_list.yaml.sample
    src_galaxy_workflow_files:
      - ../_testfiles/sample-workflow.ga
