---
driver:
  name: podman
  image_settings: &image_settings
    pre_build_image: true
    registry:
      url: $DOCKER_REGISTRY
      credentials:
        username: $DOCKER_USER
        password: $DOCKER_PW
platforms:
  - name: workspace-src-ubuntu_jammy
    image: ghcr.io/utrechtuniversity/src-test-workspace:ubuntu_jammy
    <<: *image_settings
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    published_ports:
      - 8080/tcp
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
  env:
    variable_host: all
