---
driver:
  name: podman
  image_settings: &image_settings
    pre_build_image: true
    registry:
      url: $DOCKER_REGISTRY
      credentials:
        username: $DOCKER_USER
        password: $DOCKER_PW
platforms: 
  - name: workspace-src-ubuntu_jammy
    image: ghcr.io/utrechtuniversity/src-test-workspace:ubuntu_jammy
    <<: *image_settings
    command: /sbin/init
    platform: linux/amd64
    publish:
      - "8080:8080"
provisioner:
  name: ansible
  env:
    variable_host: all
