---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Update ansible
      ansible.builtin.pip:
        name: ansible
        version: 9.4.0
        state: present
