---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Update ansible
      ansible.builtin.pip:
        name: ansible
        version: 9.4.0
        state: present

    - name: Copy local component
      ansible.posix.synchronize:
        src: ../../../
        dest: /usr/local/galaxy
        archive: false
        links: true
        recursive: true
        rsync_opts:
          - --exclude=".*"
        ssh_connection_multiplexing: true

- name: Run nginx component
  ansible.builtin.import_playbook: ../../plugin-nginx/plugin-nginx.yml
  vars:
    rsc_nginx_authorization_endpoint: http://localhost
    rsc_nginx_user_info_endpoint: http://localhost
    rsc_nginx_service_url: localhost
    nginx_enable_ssl: false
    nginx_enable_auth: true
    rsc_nginx_oauth2_application:
      client_id: foo
