---
- name: Install each required role
  command: "ansible-galaxy install -r  '{{ playbook_dir }}/requirements.yml'"
  register: galaxy_result
  changed_when: "'installed successfully' in galaxy_result.stdout"
